# This is a basic workflow to help you modify a KB and get assigned to an Editor and Approver
name: KBMOD 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  issues:
    types: [opened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      # Assigns the issue to eiterh Tim or Kevin
      - uses: Many

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Issue Assigned

      
